# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdz2k17', '0004_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEvents',
            new_name='UserEvent',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
